import React,{useEffect,useRef,useState} from 'react';
import {ArrowLeft,Gamepad2,Play,Wifi,ChevronUp,ChevronDown,ChevronLeft,ChevronRight,RotateCcw} from 'lucide-react';
import {makeControllerCommand,createTransport,controllerActions} from './tvTransport';
import {makeHello} from './tvProtocol';
import {inputForWorld,normalizeInput} from './worldController';
import {profileForWorld} from './worldInputProfiles';

export default function RemoteController({sessionId=decodeURIComponent(new URLSearchParams(location.search).get('remote')||''),onExit}){
 const [status,setStatus]=useState('connecting');const [state,setState]=useState(null);const [transport,setTransport]=useState(null);const repeatRef=useRef(null);
 useEffect(()=>{if(!sessionId)return;const t=createTransport(sessionId,{onStatus:setStatus,onMessage:m=>{if(m.type==='state')setState(m.payload)}});setTransport(t);t.send(makeHello('phone'));return()=>{clearInterval(repeatRef.current);t.close()}},[sessionId]);
 const send=(action,payload={})=>transport?.send(makeControllerCommand(action,payload));
 const world=state?.world||'space';const spec=inputForWorld(world);const ui=profileForWorld(world);
 const move=(x,z,extra={})=>{if(!state?.selectedId)return;send(controllerActions.INPUT,{objectId:state.selectedId,...normalizeInput(world,{x,z,...extra})})};
 const hold=(x,z,extra={})=>{move(x,z,extra);clearInterval(repeatRef.current);repeatRef.current=setInterval(()=>move(x,z,extra),80)};
 const release=()=>{clearInterval(repeatRef.current);repeatRef.current=null;move(0,0)};
 if(!sessionId)return <div className="remote-screen"><div className="remote-card"><div className="remote-icon">📺</div><h1>Нет кода подключения</h1><p>Открой TV режим и используй ссылку/код с экрана.</p></div></div>;
 const objects=state?.objects||[];
 return <div className="remote-screen"><div className="remote-card"><div className="remote-head"><div><span>ПУЛЬТ · {spec.input.toUpperCase()}</span><h1>Мой живой мир</h1></div><div className={`remote-status ${status}`}><Wifi size={15}/>{status==='connected'||status==='local'?'На связи':'Подключение'}</div></div><div className="remote-world"><span>{world}</span><b>{state?.selectedId?'Объект выбран':'Выбери объект'}</b></div><div className="remote-objects">{objects.length?objects.map(o=><button className={state?.selectedId===o.id?'selected':''} key={o.id} onClick={()=>send(controllerActions.SELECT,{objectId:o.id})}><span>{o.emoji||'✨'}</span><b>{o.label||o.type}</b></button>):<div className="remote-empty">Ожидаем объекты с TV…</div>}</div><div className="remote-controls-label"><b>{ui.primary}</b><span>{ui.secondary}</span></div><div className="remote-pad"><button className="pad-up" aria-label={ui.up} onPointerDown={()=>hold(0,-1)} onPointerUp={release} onPointerCancel={release} onPointerLeave={release}><ChevronUp/></button><button className="pad-left" aria-label={ui.left} onPointerDown={()=>hold(-1,0)} onPointerUp={release} onPointerCancel={release} onPointerLeave={release}><ChevronLeft/></button><button className="pad-stop" aria-label="Стоп" onPointerDown={release}>✦</button><button className="pad-right" aria-label={ui.right} onPointerDown={()=>hold(1,0)} onPointerUp={release} onPointerCancel={release} onPointerLeave={release}><ChevronRight/></button><button className="pad-down" aria-label={ui.down} onPointerDown={()=>hold(0,1)} onPointerUp={release} onPointerCancel={release} onPointerLeave={release}><ChevronDown/></button></div><button className="remote-play" disabled={!state?.selectedId} onClick={()=>send(controllerActions.PLAY,{objectId:state?.selectedId})}><Play size={28}/><span>{ui.primary}</span></button><div className="remote-grid">{[['🚀','Космос','space'],['🚗','Машинки','cars'],['🚂','Поезда','trains'],['🦖','Динозавры','dinos']].map(([emoji,label,id])=><button key={id} onClick={()=>send(controllerActions.WORLD,{world:id})}><span>{emoji}</span><b>{label}</b></button>)}</div><button className="remote-back" onClick={onExit||(()=>history.back())}><ArrowLeft size={17}/> На устройство</button><div className="remote-session"><Gamepad2 size={15}/> Сессия {sessionId}</div></div></div>
}
