import React,{useEffect,useMemo,useRef} from 'react';
import * as THREE from 'three';
import {Float} from '@react-three/drei';
import {actionTransform} from './actionAnimation';

function useTexture(url){const texture=useMemo(()=>url?new THREE.Texture():null,[url]);useEffect(()=>{if(!texture||!url)return;const loader=new THREE.TextureLoader();loader.load(url,t=>{t.colorSpace=THREE.SRGBColorSpace;texture.image=t.image;texture.needsUpdate=true},undefined,()=>{});return()=>texture.dispose()},[texture,url]);return texture}
function Mat({color,texture}){return <meshStandardMaterial color={color} map={texture||null} roughness={.72} metalness={.05}/>}
function Rocket({texture,active=false,progress=0}){const flame=useRef();useEffect(()=>{if(flame.current)flame.current.visible=active},[active]);return <group><mesh rotation={[0,0,-Math.PI/2]}><coneGeometry args={[.48,1.8,24]}/><Mat color="#ef6351" texture={texture}/></mesh><mesh position={[0,-.82,0]} rotation={[0,0,-Math.PI/2]}><coneGeometry args={[.2,.7,16]}/><meshStandardMaterial color="#ffd166"/></mesh><mesh ref={flame} position={[0,-1.2,0]} rotation={[0,0,-Math.PI/2]} scale={[1,1,.7+.5*(1-progress)]}><coneGeometry args={[.14,.65,14]}/><meshStandardMaterial color="#ff9f43" emissive="#ff9f43" emissiveIntensity={1.5}/></mesh><mesh position={[0,.05,.43]} rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[.2,.2,.12,16]}/><meshStandardMaterial color="#7dd3fc"/></mesh></group>}
function Wheel({x,z,spinning}){const ref=useRef();useEffect(()=>{if(ref.current&&!spinning)ref.current.rotation.x=0},[spinning]);return <mesh ref={ref} position={[x,-.4,z]} rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[.25,.25,.18,20]}/><meshStandardMaterial color="#20242b"/></mesh>}
function Car({texture,active=false,progress=0}){const steer=(active?Math.sin(progress*Math.PI*2)*.14:0);return <group rotation={[0,steer,0]}><mesh><boxGeometry args={[2,.55,.9]}/><Mat color="#ff9f43" texture={texture}/></mesh><mesh position={[.35,.4,0]}><boxGeometry args={[.9,.45,.75]}/><meshStandardMaterial color="#7dd3fc"/></mesh><Wheel x={-.7} z={.48} spinning={active}/><Wheel x={.7} z={.48} spinning={active}/></group>}
function Train({texture,active=false,progress=0}){const ref=useRef();useEffect(()=>{if(ref.current&&active)ref.current.rotation.x=progress*Math.PI*5},[active,progress]);return <group><mesh><boxGeometry args={[2.4,.8,1]}/><Mat color="#8b5cf6" texture={texture}/></mesh>{[-.8,0,.8].map(x=><mesh key={x} ref={x===0?ref:null} position={[x,-.58,.5]} rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[.28,.28,.18,20]}/><meshStandardMaterial color="#20242b"/></mesh>)}</group>}
function Trex({texture,active=false,progress=0}){const sway=active?Math.sin(progress*Math.PI*6)*.08:0;return <group rotation={[0,sway,0]}><mesh position={[0,.45,0]}><boxGeometry args={[1.2,.75,.6]}/><Mat color="#6fcf97" texture={texture}/></mesh><mesh position={[.78,.82,0]}><sphereGeometry args={[.42,20,20]}/><Mat color="#6fcf97" texture={texture}/></mesh><mesh position={[-.3,-.1,.08+sway]} rotation={[sway,0,0]}><cylinderGeometry args={[.13,.13,.75,12]}/><Mat color="#5aa879" texture={texture}/></mesh><mesh position={[.35,-.1,-.08-sway]} rotation={[-sway,0,0]}><cylinderGeometry args={[.13,.13,.75,12]}/><Mat color="#5aa879" texture={texture}/></mesh></group>}
export default function LivingObject3D({object,actionProgress=0,actionRunning=false}){const group=useRef();const texture=useTexture(object?.textureDataUrl||object?.drawingDataUrl);const transform=actionRunning?actionTransform(object?.type,actionProgress):null;useEffect(()=>{if(!group.current)return;group.current.position.set(0,0,0);group.current.rotation.set(0,0,0);group.current.scale.set(1,1,1)},[object?.id]);if(!object)return null;const active=actionRunning;const content=object.type==='rocket'?<Rocket texture={texture} active={active} progress={actionProgress}/>:object.type==='car'?<Car texture={texture} active={active} progress={actionProgress}/>:object.type==='train'?<Train texture={texture} active={active} progress={actionProgress}/>:<Trex texture={texture} active={active} progress={actionProgress}/>;return <Float speed={active?0:.9} rotationIntensity={active?0:.08} floatIntensity={active?0:.18}><group ref={group} position={transform?[transform.x,transform.y,transform.z]:undefined} rotation={transform?[0,transform.rot*.35,transform.rot]:undefined} scale={transform?transform.scale:1}>{content}</group></Float>}
