import React,{useEffect,useRef,useState} from 'react';
import {Canvas,Stars,Float,Text,useFrame} from '@react-three/fiber';
import {OrbitControls} from '@react-three/drei';
import LivingObject3D from './LivingObject3D';
import {defaultSpawn,tickObject} from './worldPhysics';
import {actionProgress,actionRunning} from './interactionEngine';
import {pointsForWorld,pointForObject} from './worldInteractions';
import {applyWorldInput,idleWorldMotion} from './worldMotion';
import {MotionEffects} from './motionEffects';
function WorldFloor({world}){const colors={space:'#202b5a',cars:'#627d63',trains:'#6f6a68',dinos:'#6d995b'};return <mesh rotation={[-Math.PI/2,0,0]} position={[0,-1.35,0]} receiveShadow><planeGeometry args={[12,7]}/><meshStandardMaterial color={colors[world]||colors.space} roughness={1}/></mesh>}
function DecorativeWorld({world}){if(world==='space')return <><Stars radius={45} depth={30} count={900} factor={1.8}/><mesh position={[-2,1,-2]}><sphereGeometry args={[.9,24,24]}/><meshStandardMaterial color="#5f8cff"/></mesh></>;if(world==='dinos')return <><mesh position={[-2,-.8,-1]}><coneGeometry args={[.65,1.8,16]}/><meshStandardMaterial color="#7f7056"/></mesh><mesh position={[2,-.9,-1.4]}><coneGeometry args={[.45,1.2,12]}/><meshStandardMaterial color="#6c8f55"/></mesh></>;if(world==='trains')return <><mesh position={[0,-1.15,0]}><boxGeometry args={[8,.06,.45]}/><meshStandardMaterial color="#3b3b3b"/></mesh><mesh position={[0,-1.08,.65]}><boxGeometry args={[8,.05,.08]}/><meshStandardMaterial color="#d8d8d8"/></mesh></>;return <><mesh position={[0,-1.18,0]}><boxGeometry args={[8,.08,2.1]}/><meshStandardMaterial color="#555"/></mesh><mesh position={[0,-1.12,0]}><boxGeometry args={[8,.04,.08]}/><meshStandardMaterial color="#ffd166"/></mesh></>}
function WorldPoint({point,onSelect}){const [hover,setHover]=useState(false);return <group position={[point.x,-.95,point.z]} onClick={e=>{e.stopPropagation();onSelect?.(point)}} onPointerOver={()=>setHover(true)} onPointerOut={()=>setHover(false)}><mesh scale={hover?1.15:1}><cylinderGeometry args={[.28,.34,.12,24]}/><meshStandardMaterial color="#f6d365" emissive="#6b4f00" emissiveIntensity={hover?.35:0}/></mesh><Float speed={1.2} floatIntensity={.15}><Text position={[0,.42,0]} fontSize={.17} color="white" anchorX="center">{point.emoji}</Text></Float></group>}
function MovingObject({object,index,total,onSelect,action,onEvent,manualMove}){const [motion,setMotion]=useState(()=>({...defaultSpawn(index,total),phase:index*.7,heading:0,altitude:0,velocity:0}));const fired=useRef(false);useEffect(()=>{fired.current=false},[action?.objectId,action?.startedAt]);useEffect(()=>{setMotion({...defaultSpawn(index,total),phase:index*.7,heading:0,altitude:0,velocity:0})},[object.id,index,total]);useFrame((_,delta)=>setMotion(s=>{const manual=manualMove?.objectId===object.id?manualMove:null;const running=actionRunning(action)&&action.objectId===object.id;if(manual)return {...applyWorldInput(s,manual,object.world,delta),phase:s.phase+delta};if(!running)return {...idleWorldMotion(tickObject(s,Math.min(delta,.05),object.world),delta,object.world),phase:s.phase+delta};const p=actionProgress(action);const target=pointForObject(object.world,object.type,index);if(target){const steer=Math.min(1,delta*2.8+Math.sin(p*Math.PI)*.16);const x=s.x+(target.x-s.x)*steer;const z=s.z+(target.z-s.z)*steer;if(p>.92&&!fired.current){fired.current=true;onEvent?.({type:'arrival',object,point:target})}return {...s,x,z,phase:s.phase+delta,direction:s.direction,velocity:Math.max(0.2,s.velocity||1)}}return {...s,phase:s.phase+delta}}));const running=actionRunning(action)&&action.objectId===object.id;return <group position={[motion.x,(motion.z===0?-.15:-.05)+(object.world==='space'?(motion.altitude||0):0),motion.z]} rotation={[0,motion.heading||0,0]} onClick={e=>{e.stopPropagation();onSelect?.(object)}}><LivingObject3D object={object} actionProgress={running?actionProgress(action):0} actionRunning={running}/><MotionEffects world={object.world} running={running}/></group>}
export default function LivingWorldScene({world,objects=[],selectedId,onSelect,onPoint,onWorldEvent,action,manualMove}){const [selected,setSelected]=useState(null);const [point,setPoint]=useState(null);const [eventText,setEventText]=useState('');const current=objects.filter(o=>o.world===world).slice(0,8);const points=pointsForWorld(world);useEffect(()=>{setSelected(current.find(o=>o.id===selectedId)||null);setPoint(null);setEventText('')},[selectedId,current.length,world]);useEffect(()=>{if(!eventText)return;const id=setTimeout(()=>setEventText(''),2800);return()=>clearTimeout(id)},[eventText]);const handlePoint=p=>{setPoint(p);setSelected(null);onSelect?.(null);onPoint?.(p)};const handleEvent=e=>{if(e.type==='arrival'){setEventText(`${e.point.emoji} ${e.point.label}: ${e.point.message}`);onWorldEvent?.(e);onPoint?.(e.point)}};return <Canvas camera={{position:[0,1,6.4],fov:45}} shadows fallback={<div className="canvas-fallback">3D-сцена недоступна на этом устройстве</div>} onPointerMissed={()=>{setSelected(null);setPoint(null);onSelect?.(null)}}><ambientLight intensity={1.35}/><directionalLight position={[4,6,4]} intensity={2.1} castShadow/><DecorativeWorld world={world}/><WorldFloor world={world}/>{points.map(p=><WorldPoint key={p.id} point={p} onSelect={handlePoint}/>)}{current.map((object,i)=><MovingObject key={object.id||i} object={object} index={i} total={current.length} action={action} manualMove={manualMove} onEvent={handleEvent} onSelect={item=>{setSelected(item);setPoint(null);onSelect?.(item)}}/>)}{current.length===0&&<Float><Text position={[0,.5,0]} fontSize={.28} color="white" anchorX="center">Создай свой первый объект ✨</Text></Float>}{selected&&<Float><Text position={[0,1.85,0]} fontSize={.25} color="white" anchorX="center">{selected.label||selected.name} · живёт здесь</Text></Float>}{point&&<Float><Text position={[0,1.85,0]} fontSize={.22} color="white" anchorX="center">{point.message}</Text></Float>}{eventText&&<Float><Text position={[0,1.25,0]} fontSize={.23} color="white" anchorX="center">{eventText}</Text></Float>}<OrbitControls enablePan={false} minDistance={4} maxDistance={9}/></Canvas>}
