import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Canvas,useFrame} from '@react-three/fiber';
import {OrbitControls,Stars,Float,Text} from '@react-three/drei';
import {Rocket,Car,TrainFront,Dinosaur,Camera,Play,Plus,Palette,Sparkles,X,BookOpen,Trash2,ScanLine,Check,RotateCcw} from 'lucide-react';
import {scanDrawing} from './captureEngine';
import './styles.css';

const worlds={
 space:{label:'Космос',icon:Rocket,emoji:'🚀',desc:'Ракеты, планеты и космические приключения',objects:['Ракета','Планета','Луноход']},
 cars:{label:'Машинки',icon:Car,emoji:'🚗',desc:'Гаражи, дороги и собственный автопарк',objects:['Гоночная машина','Грузовик','Пожарная машина']},
 trains:{label:'Поезда',icon:TrainFront,emoji:'🚂',desc:'Станции, мосты и большие железные дороги',objects:['Паровоз','Скоростной поезд','Грузовой поезд']},
 dinos:{label:'Динозавры',icon:Dinosaur,emoji:'🦖',desc:'Доисторический остров с динозаврами',objects:['Ти-рекс','Трицератопс','Стегозавр']}
};
function Planet(){return <mesh position={[-2,1,-2]}><sphereGeometry args={[1,32,32]}/><meshStandardMaterial color="#5f8cff" roughness={.8}/></mesh>}
function Rocket3D(){return <Float speed={1.5} rotationIntensity={.3} floatIntensity={.8}><mesh position={[1,1,0]} rotation={[0,0,-.25]}><coneGeometry args={[.45,1.6,24]}/><meshStandardMaterial color="#ff6b5f"/><mesh position={[0,-.75,0]}><coneGeometry args={[.18,.7,16]}/><meshStandardMaterial color="#ffd166"/></mesh></mesh></Float>}
function Dino(){const [x,setX]=useState(-2);useFrame((_,d)=>setX(v=>v+d*.18>2?-2:v+d*.18));return <group position={[x,-.4,0]}><mesh position={[0,.65,0]}><boxGeometry args={[1.1,.7,.55]}/><meshStandardMaterial color="#6fcf97"/></mesh><mesh position={[.7,1,0]}><sphereGeometry args={[.4,20,20]}/><meshStandardMaterial color="#6fcf97"/></mesh><mesh position={[.9,1.08,.32]}><sphereGeometry args={[.07,10,10]}/><meshStandardMaterial color="#222"/></mesh><mesh position={[-.25,.05,0]}><cylinderGeometry args={[.12,.12,.7,12]}/><meshStandardMaterial color="#5aa879"/></mesh><mesh position={[.35,.05,0]}><cylinderGeometry args={[.12,.12,.7,12]}/><meshStandardMaterial color="#5aa879"/></mesh></group>}
function Car3D(){return <group position={[0,-1,0]}><mesh><boxGeometry args={[2,.55,.9]}/><meshStandardMaterial color="#ff9f43"/></mesh><mesh position={[.35,.4,0]}><boxGeometry args={[.9,.45,.75]}/><meshStandardMaterial color="#7dd3fc"/></mesh>{[-.7,.7].map(x=><mesh key={x} position={[x,-.4,.48]} rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[.25,.25,.18,20]}/><meshStandardMaterial color="#222"/></mesh>)}</group>}
function Train3D(){return <group position={[0,-.5,0]}><mesh><boxGeometry args={[2.3,.8,1]}/><meshStandardMaterial color="#8b5cf6"/></mesh>{[-.75,0,.75].map(x=><mesh key={x} position={[x,-.6,.5]} rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[.28,.28,.18,20]}/><meshStandardMaterial color="#222"/></mesh>)}</group>}
function Scene({world}){return <Canvas camera={{position:[0,1,6],fov:45}} fallback={<div className="canvas-fallback">3D-сцена недоступна на этом устройстве</div>}><ambientLight intensity={1.4}/><directionalLight position={[4,5,4]} intensity={2}/>{world==='space'&&<><Stars radius={50} depth={30} count={1200} factor={2}/><Planet/><Rocket3D/></>}{world==='cars'&&<Car3D/>}{world==='trains'&&<Train3D/>}{world==='dinos'&&<><mesh position={[0,-1.4,0]}><boxGeometry args={[8,.2,5]}/><meshStandardMaterial color="#7acb83"/></mesh><Dino/></>}<Text position={[0,2.1,0]} fontSize={.38} color="white">Мой живой мир</Text><OrbitControls enablePan={false}/></Canvas>}

function App(){
 const [world,setWorld]=useState('space');const [toast,setToast]=useState('');const [cameraOpen,setCameraOpen]=useState(false);const [collectionOpen,setCollectionOpen]=useState(false);const [scanOpen,setScanOpen]=useState(false);const [scanResult,setScanResult]=useState(null);const [scanning,setScanning]=useState(false);const [collection,setCollection]=useState(()=>JSON.parse(localStorage.getItem('mlw-collection')||'[]'));const inputRef=useRef(null);const w=worlds[world];
 useEffect(()=>localStorage.setItem('mlw-collection',JSON.stringify(collection)),[collection]);
 const notify=(message)=>{setToast(message);window.clearTimeout(window.__mlwToast);window.__mlwToast=window.setTimeout(()=>setToast(''),2200)};
 const addObject=()=>{const name=w.objects[collection.length%w.objects.length];setCollection(v=>[{id:Date.now(),name,world,emoji:w.emoji},...v].slice(0,30));notify(`${w.emoji} ${name} добавлен в твой мир!`)};
 const openCamera=()=>setCameraOpen(true);const choosePhoto=()=>inputRef.current?.click();
 const handlePhoto=async(e)=>{const file=e.target.files?.[0];if(!file)return;setCameraOpen(false);setScanOpen(true);setScanning(true);try{const result=await scanDrawing(file);setScanResult(result)}catch(err){notify(err.message||'Не удалось обработать фото');setScanOpen(false)}finally{setScanning(false)}e.target.value=''};
 const acceptScan=()=>{if(!scanResult)return;const item={id:Date.now(),name:`Мой ${w.objects[0]}`,world,emoji:w.emoji,photo:scanResult.dataUrl,scanConfidence:scanResult.confidence};setCollection(v=>[item,...v].slice(0,30));setScanOpen(false);setScanResult(null);notify(`✨ ${w.emoji} Рисунок добавлен в ${w.label.toLowerCase()}!`)};
 const removeItem=(id)=>setCollection(v=>v.filter(x=>x.id!==id));
 return <div className="app"><input ref={inputRef} className="hidden-input" type="file" accept="image/*" capture="environment" onChange={handlePhoto}/>
  <header><div className="brand"><div className="logo">✨</div><div><b>Мой живой мир</b><span>Рисуй. Оживляй. Играй.</span></div></div><button className="parent" onClick={()=>setCollectionOpen(true)}><BookOpen size={16}/> Моя коллекция <strong>{collection.length}</strong></button></header>
  <main><section className="hero"><div><div className="eyebrow"><Sparkles size={16}/> ТВОЙ МИР</div><h1>Преврати рисунок<br/>в <em>живое приключение</em></h1><p>Раскрась ракету, машинку, поезд или динозавра — сфотографируй рисунок, и мы подготовим его для твоего мира.</p><button className="primary" onClick={openCamera}><Camera size={20}/> Оживить рисунок</button></div><div className="preview"><Scene world={world}/></div></section>
   <section className="worlds"><div className="section-title"><div><span>ВЫБЕРИ МИР</span><h2>Где будем играть?</h2></div><button className="add" onClick={addObject}><Plus size={18}/> Добавить объект</button></div><div className="cards">{Object.entries(worlds).map(([id,item])=><button className={'world-card '+(world===id?'active':'')} onClick={()=>setWorld(id)} key={id}><div className="world-icon">{item.emoji}</div><div><b>{item.label}</b><p>{item.desc}</p></div><div className="count">{item.objects.length} шаблона</div></button>)}</div></section>
   <section className="create"><div className="create-copy"><div className="eyebrow"><Palette size={16}/> СОЗДАЙ САМ</div><h2>Твоя раскраска<br/>становится <em>3D</em></h2><p>Сначала мы очищаем фото и готовим область рисунка. Следующий шаг — точное распознавание формы и перенос цветов на 3D-модель.</p><div className="steps"><span><b>01</b> Раскрась</span><span><b>02</b> Сфотографируй</span><span><b>03</b> Сканируй</span></div></div><div className="object-card"><div className="paper">{w.emoji}</div><div><b>{collection[0]?.name||'Твой объект'}</b><span>{collection.length?'Сохранён в твоей коллекции':'Создай первый рисунок'}</span></div><button onClick={openCamera}><Play size={17}/></button></div></section></main>
  {cameraOpen&&<div className="modal-backdrop" onClick={()=>setCameraOpen(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setCameraOpen(false)}><X/></button><div className="camera-icon">📸</div><h2>Оживим твой рисунок</h2><p>Положи лист ровно, чтобы были видны углы и маркеры, затем сфотографируй его при хорошем свете.</p><button className="primary wide" onClick={choosePhoto}><Camera size={20}/> Сделать фото</button><button className="secondary wide" onClick={choosePhoto}>Выбрать из галереи</button></div></div>}
  {scanOpen&&<div className="modal-backdrop"><div className="scanner-modal" onClick={e=>e.stopPropagation()}><div className="scanner-head"><div><span>СКАНЕР РИСУНКА · V1</span><h2>{scanning?'Обрабатываем рисунок':'Проверь результат'}</h2></div>{!scanning&&<button className="modal-close" onClick={()=>{setScanOpen(false);setScanResult(null)}}><X/></button>}</div>{scanning?<div className="scan-progress"><div className="scan-ring"><ScanLine size={42}/></div><b>Ищем лист и очищаем края…</b><span>Это происходит прямо на устройстве.</span></div>:scanResult&&<><div className="scan-preview"><img src={scanResult.dataUrl} alt="Обработанный рисунок"/><div className="scan-badge"><Check size={15}/> Готово</div></div><div className="scan-meta"><div><b>{Math.round(scanResult.confidence*100)}%</b><span>уверенность сканера</span></div><div><b>{scanResult.usedMarkerHint?'Маркеры':'Автокадрирование'}</b><span>режим обнаружения</span></div></div><div className="scan-actions"><button className="secondary" onClick={()=>{setScanOpen(false);setScanResult(null)}}><RotateCcw size={17}/> Переснять</button><button className="primary" onClick={acceptScan}><Check size={18}/> Добавить в мир</button></div></>}</div></div>}
  {collectionOpen&&<div className="modal-backdrop" onClick={()=>setCollectionOpen(false)}><div className="collection-modal" onClick={e=>e.stopPropagation()}><div className="collection-head"><div><span>МОЙ МИР</span><h2>Моя коллекция</h2></div><button className="modal-close" onClick={()=>setCollectionOpen(false)}><X/></button></div>{collection.length===0?<div className="empty"><div>✨</div><b>Здесь пока пусто</b><span>Создай первый рисунок и добавь его сюда.</span></div>:<div className="collection-grid">{collection.map(item=><div className="collection-item" key={item.id}>{item.photo?<img src={item.photo} alt="рисунок"/>:<div className="collection-emoji">{item.emoji}</div>}<b>{item.name}</b><span>{worlds[item.world].label}</span><button onClick={()=>removeItem(item.id)} title="Удалить"><Trash2 size={14}/></button></div>)}</div>}</div></div>}
  {toast&&<div className="toast">{toast}</div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
